
Vagrant.configure("2") do |config|

  config.vm.define "docker001" do |docker001|
    docker001.vm.box = "centos7_base"
    docker001.vm.hostname = "docker001.local"
    docker001.vm.network "private_network", type: "dhcp"
    docker001.vm.provider :virtualbox do |vb|
      vb.customize [
        "modifyvm", :id,
        "--cpuexecutioncap", "50",
        "--memory", "256",
      ]
    docker001.vm.provision :shell, :path => "bootstrap.sh"
    end
  end

end